#!/bin/sh
### BEGIN INIT INFO
# Provides:            bluetooth-agent
# Required-Start:      $local_fs $syslog dbus bluetooth
# Required-Stop:       $local_fs $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts sonos-bluetooth agent
### END INIT INFO

. /lib/lsb/init-functions

THIS=$0
BLUETOOTH_PIN=4510

case "$1" in
  start)
    log_daemon_msg "Starting bluetooth agent"
    /app/bin/passkey-agent --default $BLUETOOTH_PIN
    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping bluetooth agent"
    pkill -f passkey-agent
    log_end_msg 0
    ;;

  *)
    echo "Usage: $THIS {start|stop}"
    exit 1
    ;;
esac

exit 0
