#!/bin/sh
### BEGIN INIT INFO
# Provides:            bluetooth
# Required-Start:      $local_fs $syslog dbus
# Required-Stop:       $local_fs $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts bluetooth daemons
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/usr/libexec/bluetooth/bluetoothd
SSD_OPTIONS="--oknodo --quiet --exec $DAEMON"

case "${1}" in
  start)
    log_daemon_msg "Starting bluetooth"
    start-stop-daemon --start --background $SSD_OPTIONS
    log_progress_msg "${DAEMON}"

    hciconfig hci0 name $(cat /app/config/bluetooth-name)
    hciconfig hci0 class 0x240414
    hciconfig hci0 up > /dev/null 2>&1
    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping bluetooth"
    start-stop-daemon --stop $SSD_OPTIONS
    log_progress_msg "${DAEMON}"
    log_end_msg 0
    ;;

  restart)
    ${0} stop
    sleep 1
    ${0} start
    ;;

  status)
    status_of_proc "$DAEMON" "`basename $DAEMON`" && exit 0 || exit $?
    ;;

  *)
    echo "Usage: ${0} {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
