#!/bin/sh
### BEGIN INIT INFO
# Provides:          pulseaudio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start pulseaudio sound server in user mode
### END INIT INFO

. /lib/lsb/init-functions

RUN_AS=sonos
LOG="/var/log/`basename $0`.log"

case "$1" in
  start)
    log_daemon_msg "Starting pulseaudio as $RUN_AS..."
    su -c "pulseaudio -vvvv --start --log-target=syslog --resample-method=trivial" $RUN_AS
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping pulseaudio..."
    su -c "pulseaudio --log-target=syslog --kill" $RUN_AS
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
