#!/bin/sh
### BEGIN INIT INFO
# Provides:          pulseaudio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start pulseaudio sound server in user mode
### END INIT INFO

RUN_AS=sonos
LOG="/var/log/`basename $0`.log"

start() {
  echo "Starting pulseaudio as user \"$1\""
  su -c "pulseaudio --start" $1
}

stop() {
  echo "Stopping pulseaudio"
  su -c "pulseaudio --kill"
}

case "$1" in
  start)
    start $RUN_AS >> $LOG 2>> $LOG
    ;;
  stop)
    stop >> $LOG 2>> $LOG
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/pulseaudio {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
