#!/bin/sh
### BEGIN INIT INFO
# Provides:          sonos-bluetooth-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Configure and start sonos-bluetooth agent
### END INIT INFO

. /lib/lsb/init-functions

PIN=$(cat /app/config/pin)
BLUETOOTH_NAME=$(cat /app/config/bluetooth-name)
BLUETOOTH_CLASS="0x240414"

LOG="/var/log/`basename $0`.log"

case "$1" in
  start)
    log_daemon_msg "Configuring sonos-bluetooth..."
    hciconfig hci0 name $BLUETOOTH_NAME
    hciconfig hci0 class $BLUETOOTH_CLASS
    hciconfig hci0 sspmode 0
    log_end_msg 0

    log_daemon_msg "Enabling bluetooth scanning..."
    hciconfig hci0 up
    hciconfig hci0 piscan
    log_end_msg 0

    log_daemon_msg "Starting sonos-bluetooth agent with PIN $PIN..."
    bluetooth-agent $PIN | tee >> $LOG 2>> $LOG
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping sonos-bluetooth agent..."
    pkill -f bluetooth-agent | tee >> $LOG 2>> $LOG
    log_end_msg $?

    log_daemon_msg "Disabling bluetooth scanning..."
    hciconfig hci0 noscan
    log_end_msg 0
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
