#!/bin/sh
### BEGIN INIT INFO
# Provides:          sonos-bluetooth-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sonos-bluetooth server
### END INIT INFO

LOG="/var/log/`basename $0`.log"

start() {
  echo "Starting sonos-bluetooth server"
  /app/bin/server
}

stop() {
  echo "Stopping sonos-bluetooth server"
  pkill -f /app/bin/server
}

case "$1" in
  start)
    start >> $LOG 2>> $LOG
    ;;
  stop)
    stop >> $LOG 2>> $LOG
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/sonos-bluetooth-server {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
