#!/bin/sh
### BEGIN INIT INFO
# Provides:          sonos-bluetooth-server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sonos-bluetooth server
### END INIT INFO

. /lib/lsb/init-functions

LOG="/var/log/`basename $0`.log"

case "$1" in
  start)
    log_daemon_msg "Starting sonos-bluetooth server..."
    /app/bin/server | tee >> $LOG 2>> $LOG
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping sonos-bluetooth server..."
    pkill -f /app/bin/server | tee >> $LOG 2>> $LOG
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
